# Generated by Django 5.0.6 on 2024-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task_categories',
        ),
    ]
