# Generated by Django 5.0.6 on 2024-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task_categories'),
        ('task', '0003_remove_task_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tasks',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
