# Generated by Django 5.0.6 on 2024-07-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
    ]
