# Generated by Django 5.0.6 on 2024-07-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_tasks'),
        ('task', '0005_remove_task_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tasks',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
