# Generated by Django 5.0.6 on 2024-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task_categories'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
