# Generated by Django 5.0.6 on 2024-07-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_category',
        ),
    ]
