# Generated by Django 5.0.6 on 2024-07-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_tasks'),
        ('task', '0003_remove_task_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
